### PR TITLE
Enable the const_unsafe_cell_new feature flag for nightly

### PR DESCRIPTION
**Pull request by jedisct1**

### CODE REVIEW

**Comment by KodrAus** [comment]
Thanks @jedisct1!

This depends on https://github.com/mvdnes/spin-rs/pull/42

**Comment by KodrAus** [comment]
This looks good to me. @Kimundi are we ok to merge this and push out a point release?

**Comment by KodrAus** [comment]
Another fix for this I think would be https://github.com/rust-lang-nursery/lazy-static.rs/pull/55 which removes the need for this feature flag.

**Comment by Kimundi** [comment]
Looks good, thanks!

**Comment by joshlf** [comment]
Looks like this might not be sufficient - since the version of `spin` that's required is just `0.4`, existing `Cargo.lock` files with `0.4.5` or below will still cause breakage because `spin` only fixed this issue in `0.4.6`.

**Comment by sfackler** [comment]
It seems pretty expected that people may have to update dependencies to fix bugs?

**Comment by joshlf** [comment]
Well right now, this will just show itself as a compilation failure - it wouldn't be obvious that updating to a newer version would fix things. If we changed the dependency to `spin = 0.4.6`, then it would show itself as a failure to resolve dependencies, which would make it very obvious what needed to be done.

**Pull request merged**
