### PR TITLE
1.0 release

### PR DESCRIPTION
**Pull request by Kimundi**
This PR finally stabilizes this crate as version 1.0!

### CODE REVIEW

**Comment by KodrAus** [comment]
Woohoo! Is it safe to assume changes to the API behind the `nightly` feature aren't being SemVer tracked, since we might be forced to tweak them in breaking ways? Maybe we should mention that in the readme somewhere.

**Comment by Kimundi** [comment]
Ah, good point, I never even considered that they might be taken as stable parts of the API

**Comment by Kimundi** [comment]
Alright, I added some docs about the two features, and also cleaned up doc and metadata stuff I seem to have messed up in some recent changes.

**Comment by Kimundi** [comment]
Judging by the lack of further comments, I think it's time for the actual release now. :)

**Pull request merged**
