### PR TITLE
Spinning no_std feature

### LINKED ISSUE #44: A feature for spinning and core-only
This would be useful freestanding work.

I actually wrote this in my fork of this library already (as a change, not optional feature), but I moved the lazy implementation to https://github.com/mvdnes/spinlock-rs/blob/master/src/once.rs and would pull that as an (optional) dependency.

### PR DESCRIPTION
**Pull request by Ericson2314**
Fixes #44

### CODE REVIEW

**Comment by Ericson2314** [comment]
Ok, added a commit to get travis to test this feature too.

**Comment by Kimundi** [comment]
Thanks!

**Comment by jethrogb** [comment]
This change should've been accompanied by a minor version bump to avoid breakage.

**Comment by Ericson2314** [comment]
What broke? I didn't think I had changed any intentionally-public interfaces.

**Comment by jethrogb** [comment]
Sorry, disregard. I was confused by commit b230b7a and the reverse chronological order of the commits in the PR screen and I thought there used to be a `no_std` feature that was renamed.

**Comment by Ericson2314** [comment]
Ah, yeah the way github presents commits in PR threads is super confusing.

**Comment by BurntSushi** [comment]
FYI, I *think* this PR caused the minimum Rust version for `lazy_static` to increase with the use of `#![no_std]`. (The policy of whether that's allowed in a minor semver bump is currently being debated: https://github.com/rust-lang/rfcs/pull/1619)

**Pull request merged**
