### PR TITLE
OSX and Windows CI

### LINKED ISSUE #65: Publish CI badges for all Tier 1 platforms
Per https://github.com/brson/rust-api-guidelines#c-ci.

### PR DESCRIPTION
**Pull request by opilar**
Partially resolves #65.

### CODE REVIEW

**Comment by Kimundi** [comment]
Thanks! Could you add a new line at the end to both config files though?

**Comment by Kimundi** [comment]
Seems like osx does not like the way travis-cargo is called there.

**Comment by opilar** [comment]
Yes. Check out my issue: https://github.com/huonw/travis-cargo/issues/70

**Comment by KodrAus** [comment]
Is there anything else blocking this @Kimundi? I guess we'll need to enable AppVeyor for this repo.

**Comment by Kimundi** [comment]
Seems nothing else is blocking it. I'll merge and see if I can get appvoyer running.

**Pull request merged**
