### PR TITLE
Upgraded spin to 0.7 for better performance

### PR DESCRIPTION
**Pull request by zesterer**
`spin` 0.7 includes performance improvements such as less strict ordering requirements and better spinning. All in all, this should reduce power consumption and improve performance, particularly on platforms like ARM.

### CODE REVIEW

**Comment by zesterer** [comment]
Closes #181

**Comment by zesterer** [comment]
@KodrAus Any chance of this getting merged? Also, what do you think about using `0.7` instead of `0.7.0` to avoid compiling extra dependencies unnecessarily if `spin` already exists in the dependency tree? I'm very careful to avoid breaking changes.

**Comment by KodrAus** [comment]
Sorry for the delay here @zesterer! :bow: This looks good to me.

**Comment by zesterer** [comment]
As a point of interest: `0.9` has since been released!

**Comment by r3dlight** [comment]
Also adding this here : 
https://deps.rs/crate/lazy_static/1.4.0
https://rustsec.org/advisories/RUSTSEC-2019-0013.html

**Pull request merged**
