### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by KodrAus**

### CODE REVIEW

**Comment by KodrAus** [comment]
While I'm here we should migrate those compile tests to `trybuild` :eyes:

**Comment by smoelius** [comment]
> While I'm here we should migrate those compile tests to `trybuild` eyes

May I ask, what benefit would this provide? (This is a serious question, BTW.)

**Comment by KodrAus** [comment]
@smoelius There are two main ones I'm interested in:

1. Not needing to set up a separate project to run compile tests, since they're what exercises most of the library. `trybuild` has a simpler API to work with.
2. We might be able to get rid of some hacks we've accumulated to work around complexities in invoking Cargo the way these libraries. We've had to shim `lazy-static` to make the old tests work because it's been a dependency of the compiler.

**Comment by smoelius** [comment]
Thanks, @KodrAus. I would be curious to see what those changes would look like.

**Pull request closed without merging**
